GET {{host}}/api/jobs
Accept: application/json
###

GET {{host}}/api/jobs/7
Accept: application/json
###

POST {{host}}/api/jobs
Content-Type: application/json

{
  "url" : "https://laravel.com",
  "selectors": "body section div .relative p"
}

###

DELETE {{host}}/api/jobs/30
Accept: application/json
###
